# Production Supabase Configuration
# This configuration is optimized for production deployment with proper scaling

project_id = "customer-signal-prod"

[api]
enabled = true
# Production API configuration
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 10000  # Increased for production workloads

[auth]
enabled = true
# Production URLs - update these with your actual domain
site_url = "https://your-domain.com"
additional_redirect_urls = [
  "https://your-domain.com",
  "https://www.your-domain.com",
  "https://app.your-domain.com"
]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true  # Enable email confirmations in production

[auth.external.google]
enabled = false
client_id = ""
secret = ""

[auth.external.github]
enabled = false
client_id = ""
secret = ""

[db]
# Production database configuration
major_version = 15
# Connection pooling settings for production
pool_size = 15
max_client_conn = 100
default_pool_size = 20
default_to_null = true

[realtime]
enabled = true
# Production realtime configuration
max_concurrent_users = 200

[storage]
enabled = true
file_size_limit = "100MiB"  # Increased for production
# Production storage buckets
buckets = [
  { name = "reports", public = false },
  { name = "uploads", public = false },
  { name = "exports", public = false }
]

[analytics]
enabled = true  # Enable analytics in production

[functions]
# Edge Functions configuration for production
verify_jwt = true

[experimental]
# Enable experimental features for better performance
webhooks = true